CREATE EXTERNAL TABLE IF NOT EXISTS [your database].network (
  benchmark_version CHAR(8),
  collectd_rrd VARCHAR(255),
  dns_recursive TINYINT,
  dns_servers TINYINT,
  iteration TINYINT,
  meta_compute_service CHAR(32),
  meta_compute_service_id CHAR(24),
  meta_cpu CHAR(32),
  meta_cpu_cache CHAR(32),
  meta_geo_region CHAR(32),
  meta_hostname CHAR(64),
  meta_instance_id CHAR(96),
  meta_location CHAR(32),
  meta_location_country CHAR(2),
  meta_location_state CHAR(32),
  meta_memory CHAR(32),
  meta_memory_gb SMALLINT,
  meta_memory_mb INT,
  meta_os_info CHAR(32),
  meta_provider CHAR(32),
  meta_provider_id CHAR(24),
  meta_region CHAR(32),
  meta_resource_id CHAR(32),
  meta_run_id CHAR(32),
  meta_test_id CHAR(64),
  metric FLOAT,
  metric_10 FLOAT,
  metric_25 FLOAT,
  metric_75 FLOAT,
  metric_90 FLOAT,
  metric_fastest FLOAT,
  metric_max FLOAT,
  metric_mean FLOAT,
  metric_min FLOAT,
  metric_rstdev FLOAT,
  metric_slowest FLOAT,
  metric_stdev FLOAT,
  metric_sum FLOAT,
  metric_sum_squares FLOAT,
  metric_timed FLOAT,
  metric_unit CHAR(8),
  metric_unit_long CHAR(32),
  metrics VARCHAR(255),
  samples TINYINT,
  status CHAR(8),
  tcp_file VARCHAR(64),
  test CHAR(12),
  test_endpoint VARCHAR(64),
  test_geo_region CHAR(32),
  test_instance_id VARCHAR(96),
  test_ip CHAR(16),
  test_location CHAR(32),
  test_location_country CHAR(2),
  test_location_state CHAR(32),
  test_private_endpoint TINYINT,
  test_private_network_type VARCHAR(64),
  test_provider CHAR(32),
  test_provider_id CHAR(24),
  test_region CHAR(32),
  test_service CHAR(32),
  test_service_id CHAR(24),
  test_service_type CHAR(8),
  test_started TIMESTAMP,
  test_stopped TIMESTAMP,
  tests_failed SMALLINT,
  tests_success SMALLINT,
  throughput_custom_cmd TINYINT,
  throughput_https TINYINT,
  throughput_keepalive TINYINT,
  throughput_size FLOAT,
  throughput_small_file TINYINT,
  throughput_threads TINYINT,
  throughput_time TINYINT,
  throughput_transfer FLOAT,
  timeout TINYINT,
  traceroute VARCHAR(255)
)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
  ESCAPED BY '\\'
  LINES TERMINATED BY '\n'
LOCATION 's3://[your S3 bucket]/path/to/csv/files/'
TBLPROPERTIES (
  'skip.header.line.count'='1'
);